export const  countries = {
    countries: [
      "United States of America",
      "United Kingdom (UK)",
      "Canada",
      "Australia",
      "France",
      "Germany",
      "Italy",
      "Japan",
      "South Korea",
      "India",
      "Spain",
      "China",
      "Mexico",
      "Brazil",
      "Russia",
      "Sweden",
      "Norway",
      "Denmark",
      "Netherlands",
      "Argentina",
      "Belgium",
      "Finland",
      "Ireland",
      "New Zealand",
      "Switzerland",
      "Austria",
      "Poland",
      "Turkey",
      "Greece",
      "Hungary",
      "Czech Republic",
      "Israel",
      "Portugal",
      "South Africa",
      "Thailand",
      "Egypt",
      "Indonesia",
      "Taiwan",
      "Colombia",
      "Chile",
      "Philippines",
      "Malaysia",
      "Singapore",
      "Iceland",
      "Romania",
      "Ukraine",
      "Peru",
      "Croatia",
      "Bulgaria",
      "Saudi Arabia"
    ]
  }